# Generated by Django 4.2.2 on 2023-08-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_web_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='category',
            field=models.IntegerField(choices=[(1, 'ข่าวประกาศ'), (2, 'โฆษณา'), (3, 'บันทึก')], default=1),
        ),
    ]
